### ISSUE TITLE
Incorrect homepage in Cargo.toml of ratelimit

### ISSUE THREAD

**Issue by ulrichstark** [pelikan-io/rustcommon#122]
https://github.com/pelikan-io/rustcommon/blob/d0b010cc5385b7e39ae8b288458f6671f13d4487/ratelimit/Cargo.toml#L8

The current homepage returns HTTP 404.
You probably meant `https://github.com/pelikan-io/rustcommon/tree/main/ratelimit` or `https://github.com/pelikan-io/rustcommon` instead.
Thanks for your work and helpful crate!

**Comment by brayniac** [comment]
Thanks for reporting this. I'll get that fixed.

**Comment by brayniac** [comment]
Fixed by #126 and releases have been published with corrected links. Thanks again for reporting.
