### ISSUE TITLE
Ratelimit not working in Ubuntu 22

### ISSUE THREAD

**Issue by ktjd123** [pelikan-io/rustcommon#33]
One line summary of the issue here.

### Expected behavior

should wait on wait() call

As concisely as possible, describe the expected behavior.

### Actual behavior

not waiting or get refilled immediately, So not waiting at all.

As concisely as possible, describe the observed behavior.

### Steps to reproduce the behavior

Make a rate limiter and run it on Ubuntu.

Please list all relevant steps to reproduce the observed behavior.

Thank you and appreciate your works.

**Comment by brayniac** [comment]
@ktjd123 - can you please share the parameters for the ratelimiter?

**Comment by ktjd123** [comment]
@brayniac Hi, Thank you for answer, It was made with `Ratelimiter::new(1, 1, 20),`

**Comment by brayniac** [comment]
This was fixed by #37
