### ISSUE TITLE
`clocksource` does not support windows

### ISSUE THREAD

**Issue by rushiiMachine** [pelikan-io/rustcommon#90]
`clocksource` (and in turn, `ratelimit`) relies on an UNIX time API, making this library unusable on other platforms

https://github.com/pelikan-io/rustcommon/blob/89633481ec10e7ca1f389522471f22de54afba04/clocksource/src/precise/instant.rs#L29-L35

### Expected behavior

Use either
1. `std::time::Instant` instead which already provides all [platform implementations](https://doc.rust-lang.org/std/time/struct.Instant.html#underlying-system-calls)
2. `Instant` doesn't seem to provide raw ns values, so to avoid rewriting half the lib but I found a different lib that [does](https://docs.rs/quanta/0.12.1/quanta/struct.Clock.html#method.raw): [quanta](https://crates.io/crates/quanta)

**Comment by brayniac** [comment]
Thanks for opening this. We need the raw times in clocksource for a variety of reasons. Neither the std library nor `quanta` really fit the specific needs. 

I believe clocksource should just be extended to provide coverage for other platforms as-needed.

**Comment by brayniac** [comment]
This is fixed by #92  - new versions of all crates are published. Please open a new issue if you discover any problems.
